### ISSUE TITLE
Format requirements for the “mutationTable“ and “pairs“

### ISSUE THREAD

**Issue by jingyu9603** [argymeg/breakclone#4]
argymeg Hello,

Thank you very much for developing the breakclone software package. 

I would like to apply it to my data. However, unfortunately, I have not seen detailed data format requirements for the` mutationTable` and `pairs` parameters needed to run the software. Could you please provide a detailed description of the relevant data formats or give me a reference file if it's convenient for you.

YJ

**Comment by marromesc** [comment]
Dear YJ,

Thank you for your message.

Just so you know, we have moved **breakclone** to the [lab's repo](https://github.com/Sawyer-s-Group/breakclone), which includes some extra visualization functions. We will add some more detailed vignettes there in the future.  


In the meantime, a brief description of the data format requirements:

```r
head(mutationTable)
#>    SampleID Chr       Pos     AF annotation
#> 1:  s1  17   7674230 0.4489       TP53
#> 2:  s1  17   7675088 0.3202       TP53
#> 3:  s1  17   7675088 0.9669       TP53
#> 4:  s1   3 179218303 0.4335     PIK3CA
#> 5:  s1   3 179218303 0.6620     PIK3CA
#> 6:  s1   3 179218303 0.6518     PIK3CA

head(pairs)
#>    Sample1 Sample2
#>  1: s1 s2
#>  2: s3 s4
#>  3: s5 s6
#>  4: s7 s8
#> 5: s9 s10
#> 6: s11 s12
```

Please note these objects are of class `data.table`, which can be transformed from a `data.frame` using the `data.table::as.data.table()` function.

Kind regards,
Maria
